version: "3.9"
services:
  web:
    image : restful-cake
    ports:
      - 3000:3000
    depends_on:
      - mysql
    networks:
      backend:
        ipv4_address: 172.21.0.2
  mysql:
    command: --disable-partition-engine-check
    image: mysql:5.7
    restart: always
    container_name: godockerDB
    environment:
      MYSQL_HOST : mysql
      MYSQL_DATABASE: cake_store
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3307:3307
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
      - ./my-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      backend:
        ipv4_address: 172.21.0.3
networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
volumes:
  my-db:
